server:
  port: 8081

logging:
  level:
    root: info


#spring:
#  cloud:
#    nacos:
#      config:
#        namespace: e1c19595-0757-4231-89cb-19ea2db3bd8d
#        group: orienlink
#        server-addr: 10.10.2.98:8858

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.2.98:3316/db_test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.lucumt.model,com.lucumt.vo
  type-handlers-package: com.lucumt.handler.mybatis